[package]
authors = ["tom"]
name = "time_lock_puzzles"
version = "0.1.0"

[dependencies]
num = "0.1.41"
rand = "0.3.1"
rust-crypto = "0.2.36"
rusty_secrets = "0.0.2"
time_lock_puzzles = { path = "." }
